apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplesite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ITBeyder/simplesite
    targetRevision: main
    path: templates
  destination:
    server: "https://kubernetes.default.svc"
    namespace: simplesite

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true